global using System;
// global using EntityFramework;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using DocAPI.Utils;
global using DocAPI.Models;
// global using DocAPI.Identity;
global using .Models;
global using .Interface;
global using .DataStore;
global using Microsoft.Extensions.DependencyInjection;