# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'ali-hu'
    runOptions: 'inline'
    inline: |
      cd /var/source/DevPlatform
      # 获取新代码
      sudo git checkout .
      # 分支
      sudo git checkout master
      sudo git pull
      # 还原包
      cd /var/source/DevPlatform/app/App.Api
      sudo dotnet restore -r ubuntu.16.04-x64
      
      # 发布
      cd /var/source/OnlineTeaching/src/App.Api
      sudo dotnet publish -c release -r ubuntu.16.04-x64 -o  /var/publish/onlineTeach
      cd /var/publish/onlineTeach
      sudo cp -rf . /var/web/onlineTeach
    failOnStdErr: false
    readyTimeout: '20000'